---
permalink: /:categories/:year/:month/:day/:title
auto: true
rdiscount:
  extensions: [smart]

title: Rizcraft
author:
  name: Eris
  email: eris.discord@gmail.com
  twitter: erisdev

production_url: http://vidius.github.io/rizcraft

BASE_PATH: /rizcraft